import React from "react";
import MainWrapper from "./styled-components/MainWrapper";
import CvWrapper from "./styled-components/CvWrapper";
import FullSection from "./styled-components/FullSections";
import {
  name,
  address1,
  address2,
  mail,
  phone,
  github,
  legalNote,
} from "./data/PersonalData";

const Projects = () => {
  return (
    <MainWrapper>
      <CvWrapper>
        <FullSection>
          <h1 className="name">{name}</h1>
          <h2 className="title" style={{ marginTop: "-8px" }}>
            <em>Frontend Developer - Projects</em>
          </h2>
          <hr />
          <ul>
            <li className="list-parent">
              <p style={{ marginTop: "15px" }}>
                <strong>Grupa Pracuj S.A.</strong>
              </p>
              <ul style={{ marginTop: "15px" }}>
                <li>Developing web app in Next.js</li>
                <li>Maintaining old web app in Next.js</li>
                <li>Implementing UI design from Figma</li>
                <li>Writing unit tests</li>
                <li>Code review</li>
                <li>
                  <strong>Tech stack:</strong> React / Next.js, Rollup,
                  react-query, react-testing-library
                </li>
              </ul>
            </li>
            <li className="list-parent">
              <p>
                <strong>CS Group S.A / Panorama Firm / WeNet S.A.</strong>
              </p>
              <p style={{ marginTop: "15px" }}>As frontend developer</p>
              <ul style={{ marginTop: "15px" }}>
                <li>
                  Build from scratch website audytseo.wenet.pl in React / Gatsby
                </li>
                <li>
                  Build from scratch internal frontend application for analyzing
                  seo for websites in React
                </li>
                <li>Implementing UI design from Adobe XD</li>
                <li>
                  Creating templates for websites in FreeMarker (example:
                  budownictwo.pl) for spring boot backend
                </li>
                <li>
                  Creating templates for pdf's generated by internal
                  applications in FreeMarker for spring boot backend
                </li>
                <li>
                  <strong>Tech stack:</strong> React, Gatsby, FreeMarker,
                  react-testing-library,
                </li>
              </ul>
              <p>As SEO specialist</p>
              <ul style={{ marginTop: "15px" }}>
                <li>
                  Implementing content from copywriters on websites (plain HTML,
                  Wordpress, Drupal, Joomla, Custom solution cms)
                </li>
                <li>Optimizing pagespeed for Google's PageSpeed Insights</li>
                <li>
                  Adding new features on websites (JavaScript, jQuery, PHP)
                </li>
                <li>Fixing HTML semantics</li>
                <li>
                  <strong>Tech stack:</strong> Anything that was needed to work
                  on client's project
                </li>
              </ul>
            </li>
          </ul>
          <hr />
          <p>
            <strong>Other tech stack: </strong>Lerna, pnpm, Gitlab, Puppeter,
            Jest, Svelte, PHP, Laravel, Node, Express
          </p>
        </FullSection>
      </CvWrapper>
    </MainWrapper>
  );
};

export default Projects;
